### ISSUE TITLE
Action can't find my package.json

### ISSUE THREAD

**Issue by steveoh** [agrc/release-composite-action#114]
This action assumes the package.json is at the root of the project but mine is buried in a folder. 

Can an input be added to allow the path to the package.json to be set as an input which I think would then set the working-directory for certain parts of the action?

**Comment by stdavis** [comment]
What project is this question referencing?

**Comment by steveoh** [comment]
Parole and probation and uic follow the same pattern

**Comment by stdavis** [comment]
Have you tried setting a default working directory for the workflow like this?
![image](https://github.com/user-attachments/assets/d5cfaecf-6729-45c4-9d5d-ad35ae678f4c)

**Comment by steveoh** [comment]
Yes but without setting a shell. 

You can see my attempts in the history here. 

https://github.com/agrc/parole-and-probation/actions/workflows/push.yml

**Comment by stdavis** [comment]
Shall we close this as won't fix with the work around being use a simple release type and the extra-files input?
